FROM python:3.12-alpine
ENV TZ "Europe/Moscow"
WORKDIR /app
RUN apk update
RUN apk add git build-base g++ linux-headers python3-dev

COPY app/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ /app/

CMD ["python3", "/app/main.py"]
