name: CI Pipeline

on:
  push:
    branches: [ master, development ]
  pull_request:

jobs:
  ci:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files

      - name: Run Tests
        run: |
          docker compose -f docker-compose.test.yml up --build --abort-on-container-exit
